# Generated by Django 5.1.1 on 2024-10-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='ars.role'),
        ),
    ]
