# Generated by Django 5.1.1 on 2024-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ars', '0002_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('reviewee', 'Reviewee')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
